Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron all
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron excit
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron inhib
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron 0
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron 1
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron 2
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron 3
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron 4
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron 5
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE_neuron.R neuron 6