Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron all
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron inhib
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron 0
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron 1
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron 2 
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron 3
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron 4
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron 5
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/ADADvsCO/DE_Nebula_ADAD_Neuron.R neuron 6