Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R astro all 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R astro 0 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R astro 1 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R astro 2 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R astro 3 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R astro 4 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia all 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 0 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 1 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 2 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 3 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 4 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 5 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 6 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 7 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R microglia 8 50
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo all 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 0 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 1 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 2 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 3 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 4 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 5 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 6 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 7 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R oligo 8 60
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc all 66
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc 0 66
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc 1 66
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc 2 66
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc 3 66
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc 4 66
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc 5 66
Rscript /home/bnovotny/single_nuclei/nebula_scripts/DE_Nebula_APOE.R opc 6 66
