Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R astro all
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R astro 0
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R astro 1 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R astro 2 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R astro 3 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R astro 4 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo all
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 0
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 1 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 2 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 3 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 4 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 5 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 6 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 7 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R oligo 8 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc all
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc 0
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc 1 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc 2 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc 3 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc 4 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc 5 
Rscript /home/bnovotny/single_nuclei/DE_Nebula_ADAD.R opc 6 