Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 0 1 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 0 2 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 0 3 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 0 4
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 0 all
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 1 2
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 1 3 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 1 4 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 1 all 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 2 3 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 2 4 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 2 all 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 3 4 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 3 all 
Rscript /home/bnovotny/single_nuclei/astrocyte/DE_Nebula_astrocyte.R 4 all