Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 1 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 2 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 3 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 4 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 5 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 6 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 7 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 0 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 1 3 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 1 4 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 1 5 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 1 6 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 1 7 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 1 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 1 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 2 3 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 2 4 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 2 5 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 2 6 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 2 7 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 2 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 2 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 3 4 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 3 5 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 3 6 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 3 7 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 3 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 3 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 4 5 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 4 6 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 4 7 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 4 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 4 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 5 6 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 5 7 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 5 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 5 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 6 7 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 6 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 6 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 7 8 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 7 all 
Rscript /home/bnovotny/single_nuclei/oligodendrocyte/DE_Nebula_oligo.R 8 all 
