Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron all
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron excit
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron inhib
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron 0
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron 1
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron 2
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron 3
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron 4
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron 5
Rscript /home/bnovotny/single_nuclei/neuron/nebula_de/DE_by_status/sADvsCO/DE_Nebula_sAD_Neuron_noTREM2.R neuron 6