Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 0 2
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 0 6
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 0 all
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 1 2
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 1 6
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 1 all
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 2 6
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 2 all
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 6 all
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 3 4
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 3 5
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 3 all
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 4 5
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 4 all
Rscript /home/bnovotny/single_nuclei/neuron/DE_Nebula_neuron.R 5 all
