Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 0 2 
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 0 3 
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 0 4
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 0 5
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 0 6
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 0 all
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 1 2
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 1 3 
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 1 4
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 1 5
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 1 6
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 1 all 
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 2 3 
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 2 4
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 2 5
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 2 6
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 2 all 
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 3 4
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 3 5
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 3 6
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 3 all 
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 4 5
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 4 6
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 4 all
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 5 6
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 5 all
Rscript /home/bnovotny/single_nuclei/opc/DE_Nebula_OPC.R 6 all